#!/bin/bash
# postinstall of tech.blackdeep.knaif.model — "download the AI model now" (D13).
#
# build-pkg.sh installs this as `postinstall` beside a generated model.env naming MODEL, read from
# the model manifest the payload ships (never typed by hand). The model lands in the console user's
# ~/.knaif/models, which `models pull` also keeps out of Time Machine (D18).
#
# The download is queued, not run: it runs in the Terminal window the finish package opens at the
# end of setup, where `models pull` draws its progress bar (common.sh, QUEUE). Skipped, never
# failed, when it is already there or nobody is logged in.

here="$(dirname "$0")"
# shellcheck source=common.sh
. "$here/common.sh"
# shellcheck disable=SC1091  # generated by build-pkg.sh
. "$here/model.env"

knaif="$KNAIF_ROOT/bin/knaif"
retry="knaif models pull $MODEL"

user="$(console_user)"
if [ -z "$user" ]; then
  log "skipping the model download: nobody is logged in to download it for. Later: $retry"
  exit 0
fi
if as_user "$user" "$knaif" models list 2>/dev/null |
  awk -v m="$MODEL" '$1 == m && $2 == "installed" { found = 1 } END { exit !found }'; then
  log "$MODEL is already installed for $user"
  exit 0
fi

queue_step "The knaif AI model, $MODEL (~2.5 GB, one time)" "$retry" "$knaif" models pull "$MODEL"
log "the $MODEL download runs in a Terminal window at the end of setup"
exit 0
