#!/bin/bash
# postinstall of tech.blackdeep.knaif.tool.<name> — one supporting tool via Homebrew (D13).
#
# build-pkg.sh installs this as `postinstall` beside a generated tool.env naming the tool:
#   TOOL_NAME   display name (FFmpeg)
#   BREW_NAME   formula or cask name, mirroring skill.yaml's macos.brew
#   BREW_CASK   1 for a cask (brew install --cask), else 0
#   SKILL       the skill that uses it; skipped when that skill was not installed
#
# The install is queued, not run: it runs in the Terminal window the finish package opens at the
# end of setup, as the console user (Homebrew refuses root), where brew shows its progress and can
# ask for a password (common.sh, QUEUE). Skipped, never failed, when the skill was deselected,
# Homebrew is absent (the options page greys the choice out then; this guards a headless
# install), or nobody is logged in.

here="$(dirname "$0")"
# shellcheck source=common.sh
. "$here/common.sh"
# shellcheck disable=SC1091  # generated by build-pkg.sh
. "$here/tool.env"

cask=()
[ "$BREW_CASK" = 1 ] && cask=(--cask)
retry="brew install ${cask[*]}${cask[*]:+ }$BREW_NAME"

if [ ! -d "$KNAIF_ROOT/skills/$SKILL" ]; then
  log "skipping $TOOL_NAME: the $SKILL skill was not installed"
  exit 0
fi
if ! brew="$(find_brew)"; then
  log "skipping $TOOL_NAME: Homebrew is not installed (https://brew.sh). Later: $retry"
  exit 0
fi
user="$(console_user)"
if [ -z "$user" ]; then
  log "skipping $TOOL_NAME: nobody is logged in to install it for. Later: $retry"
  exit 0
fi

# NO_INSTALL_UPGRADE: an installed but outdated tool is the user's to upgrade, not setup's.
queue_step "$TOOL_NAME, with Homebrew" "$retry" \
  env HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_UPGRADE=1 "$brew" install "${cask[@]}" "$BREW_NAME"
log "installing $TOOL_NAME with Homebrew runs in a Terminal window at the end of setup"
exit 0
