"""Generate the third-party Python license report (`just licenses-python`).

The Rust side has `cargo about` (see about.toml / `just licenses`); this is the
Python equivalent. It walks the *runtime* dependency closure of the distributed
`knaif` package — not dev/test tooling, which is never shipped — and emits each
package's license identifier plus the full license text where the installed
distribution carries one.

Run inside the project environment so the closure resolves against what actually
ships:  uv run python scripts/gen_python_licenses.py
"""

from __future__ import annotations

import importlib.metadata as md
import re
import sys
from collections import deque
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "installers" / "licenses" / "THIRD-PARTY-PYTHON.txt"

# Runtime dependencies of the distributed wheel (python/core/pyproject.toml).
# `llama-cpp-python` is an optional extra and is deliberately excluded: it is not
# installed by a default `pip install knaif`, and its own bundled llama.cpp
# license already ships as installers/licenses/llama.cpp-LICENSE.txt.
ROOTS = ["requests", "pyyaml", "click"]

# Permissive-only, mirroring about.toml's `accepted` list for the Rust tree.
ALLOWED = re.compile(
    r"\b(MIT|BSD|Apache|ISC|Zlib|MPL[- ]?2|Mozilla Public License 2|"
    r"Unicode|CC0|BSL|0BSD|Python Software Foundation|PSF)\b",
    re.IGNORECASE,
)
FORBIDDEN = re.compile(r"\b(A?GPL|LGPL|SSPL|proprietary|commercial)\b", re.IGNORECASE)


def norm(requirement: str) -> str:
    """Reduce a requirement string ('urllib3<3,>=1.26') to a bare package name."""
    name = re.split(r"[\s;\[<>=!~(]", requirement.strip(), maxsplit=1)[0]
    return name.lower().replace("_", "-").strip()


def license_of(meta) -> str:
    expr = (meta.get("License-Expression") or "").strip()
    if expr:
        return expr
    classifiers = [c for c in meta.get_all("Classifier") or [] if c.startswith("License ::")]
    if classifiers:
        return "; ".join(c.split(" :: ")[-1] for c in classifiers)
    raw = (meta.get("License") or "").strip()
    return raw.splitlines()[0][:80] if raw else "UNKNOWN"


def license_text(dist) -> str | None:
    """Return the packaged license text, if the distribution ships one.

    Resolve through dist.locate_file(): entries in dist.files are relative to
    site-packages, whereas dist.read_text() resolves relative to the .dist-info
    directory -- using the latter silently finds nothing.
    """
    candidates = []
    for f in dist.files or []:
        name = Path(str(f)).name.upper()
        if not name.startswith(("LICENSE", "LICENCE", "COPYING", "NOTICE")):
            continue
        if name.endswith((".py", ".pyc")):
            continue
        candidates.append(f)
    # Prefer the primary LICENSE over per-vendored-dependency ones.
    candidates.sort(key=lambda f: (len(str(f)), str(f)))
    for f in candidates:
        try:
            text = Path(dist.locate_file(f)).read_text(encoding="utf-8", errors="replace")
        except (OSError, ValueError):
            continue
        if text.strip():
            return text
    return None


def collect() -> list[tuple[str, str, str, str | None]]:
    seen: set[str] = set()
    rows: list[tuple[str, str, str, str | None]] = []
    queue = deque(ROOTS)
    while queue:
        name = norm(queue.popleft())
        if not name or name in seen:
            continue
        seen.add(name)
        try:
            dist = md.distribution(name)
        except md.PackageNotFoundError:
            rows.append((name, "-", "NOT INSTALLED (platform-gated extra)", None))
            continue
        rows.append((name, dist.version, license_of(dist.metadata), license_text(dist)))
        for req in dist.requires or []:
            # Skip extras-gated requirements; they are not part of a default install.
            if ";" in req and "extra ==" in req.split(";", 1)[1]:
                continue
            queue.append(req)
    return sorted(rows)


def main() -> int:
    rows = collect()

    violations = [(n, lic) for n, _, lic, _ in rows if FORBIDDEN.search(lic)]
    unknown = [
        (n, lic) for n, _, lic, _ in rows if not ALLOWED.search(lic) and not FORBIDDEN.search(lic)
    ]

    lines = [
        "Third-party Python dependencies bundled with knaif",
        "=" * 78,
        "",
        "Generated by scripts/gen_python_licenses.py (`just licenses-python`).",
        "Covers the RUNTIME dependency closure of the distributed `knaif` wheel.",
        "Development and test tooling (pytest, black, ruff, mypy) is excluded --",
        "it is never distributed. The optional `llama` extra is excluded for the",
        "same reason; llama.cpp's own license ships as llama.cpp-LICENSE.txt.",
        "",
        f"{len(rows)} packages in the runtime closure.",
        "",
        "-" * 78,
        "SUMMARY",
        "-" * 78,
        "",
        f"{'PACKAGE':<24}{'VERSION':<14}LICENSE",
    ]
    for name, version, lic, _ in rows:
        lines.append(f"{name:<24}{version:<14}{lic}")

    lines += ["", "-" * 78, "FULL LICENSE TEXTS", "-" * 78, ""]
    for name, version, lic, text in rows:
        lines += ["=" * 78, f"{name} {version} -- {lic}", "=" * 78, ""]
        lines.append(
            text.strip() if text else f"(No license file packaged; declared license: {lic})"
        )
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows)} packages)")

    if violations:
        print(
            f"ERROR: copyleft/proprietary license in runtime closure: {violations}", file=sys.stderr
        )
        return 1
    if unknown:
        print(f"WARNING: unrecognized license, review manually: {unknown}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
